config/routes.rb
Rails.application.routes.draw do
  root 'binaries#index'
  resources :binaries do 
    collection do 
     post 'binary-search'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/number.rb
class Number < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/binaries_controller.rb
class BinariesController < ApplicationController
  before_action :set_number, only: [:index]
  def index
  end

  def binary_search 
    @numbers = params[:numbers]  ##hidden_fieldから送られた数字をインスタンス変数に代入
    unless @numbers ##送られた値が存在しなければ処理を終了。JSにindex=0を渡す。このindexが「検索結果が見つからなかった場合のポップアップと対応する。」
      index = 0
       return render json: { index: index } 
    end
    #検索対象の一番左と一番右を変数化
    left = 0
    right = @numbers.length - 1

    center = (left + right) / 2.0 #2.0で割らないと@numbersの要素数が偶数のときに中央値が正しく出ない。
    if @numbers.length % 2 == 0
      center_number = (@numbers[@numbers.length/2 -1].to_i + @numbers[@numbers.length/2].to_i)/2.0 #要素数が偶数の場合中央の値は真ん中2つの平均になる  
    else
      center_number = @numbers[center].to_i #要素数が奇数のときは中央の値は配列からcenter番目の要素を取り出す
    end

    target_number = params[:target].to_i #params[:target]はtext_fieldから飛んでくるのでstringになっているためto_iで数字に変換

    if center_number == target_number
      @deleted_numbers = @numbers.reject{ |n| n.to_i == center_number } #中央の値と検索対象の値が等しい時、中央の値以外の要素を検索対象から除外する
      index = 1
      render json: { deleted_numbers: @deleted_numbers, target: target_number, index: index }
    elsif center_number < target_number
      @deleted_numbers = @numbers[left.floor..center]   #中央の値のほうが小さい場合、検索対象の一番左から真ん中までを検索対象から除外する
      index = 2   
      left = center + 1
      render json: { deleted_numbers: @deleted_numbers, target: target_number, index: index }
    else
      @deleted_numbers =  @numbers[center.ceil..right]   #中央の値のほうが大きい場合、中央から一番右の値までを検索対象から除外する
      index = 3
      right = center - 1
      render json: { deleted_numbers: @deleted_numbers, target: target_number, index: index }
    end
  
  end

  private 

  def array_params
    params.require(:key_array).permit(numbers: [])    
  end

  def set_number 
    @number_data = Number.all.sample(50).sort #DB内にある100個の数字からランダムに50個取得して小さい順に並べる
    @numbers = []

    @number_data.each do |number| 
      @numbers << number.number #findで取ってこれるのはあくまでモデルデータなので数字だけを表示するために空配列に代入し直す
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/binaries_helper.rb
module BinariesHelper
end

app/views/binaries/index.html.erb
<div class="container">
<h1><%= link_to 'BinarySearch', root_path, class: 'title' %></h1>
<div class="description">
 <span>使い方</span>
 <ol>
  <li>検索したい数字をフォームに入力します。</li>
  <li>検索した値と数列の中央の値を比較します。</li>
  <li>検索した値が中央の値より大きければ右半分、小さければ左半分のみが黒く表示され、検索対象から外れた数字は透明になります。</li>
  <li>1~3を繰り返し、検索したい数字が見つかれば赤字で表示されます。検索した結果見つからなかった場合も含めポップアップが出ますので、ポップアップを閉じて、画面右のSet Arrayのボタンを押してください。</li>
 </ol>
</div>
<%# 検索が終了した後再度検索するためのボタン %>
<%= link_to 'Set Array' , root_path, class: 'link' %>
<%= form_with url: binary_search_binaries_path, id: 'number-form' do |f| %>
<div class="numbers">
<% @numbers.each do |number| %>
<%# 実際に表示されている数字。idはJSで透明化させるときに使う %>
 <p class="number" id=<%=number%>><%= number %></p>
 <%# ここから検索対象となる配列の数字のデータを飛ばす %>
 <%= f.hidden_field :numbers, name: 'numbers[]', value: number, id: "input_#{number}" %>
<% end %>
</div>
<%# 検索したい数字を入力 %>
 <%= f.text_field :target, class: 'search-number', placeholder: '検索したい数字を入力してください' %>
 <%= f.submit 'submit', class: 'submit'%>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BinarySearch</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>